# -*- coding: utf-8 -*-
"""coco128_training.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13FqeQX8jGWKA8JLrD59PzrGI5G8xZFHc
"""

!git clone https://github.com/ultralytics/yolov5

!pip install -qr yolov5/requirements.txt

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov5

from google.colab import drive
drive.mount('/content/drive')

import torch
from IPython.display import Image, clear_output
from utils.google_utils import gdrive_download

clear_output()

print('Setup complete. Using torch %s %s' % (torch.__version__, torch.cuda.get_device_properties(0) if torch.cuda.is_available() else 'CPU'))

!python detect.py --weights yolov5s.pt --img 416 --conf 0.4 --source inference/images/

Image(filename='inference/output/zidane.jpg', width=600)

Image(filename='inference/output/bus.jpg', width=600)

gdrive_download('1n_oKgR81BJtqk75b00eAjdv03qVCQn2f','coco128.zip')  # coco128 dataset

!mv ./coco128 ../

!git clone https://github.com/mobile44/yolo128_tee.git

!pwd
!mv ./yolo_coco128_tee/data/coco128.yaml ./data/
!mv ./yolo_coco128_tee/images/test/* ./inference/images/
!mv ./yolo_coco128_tee/images/train/* ../coco128/images/train2017/
!mv ./yolo_coco128_tee/labels/train/* ../coco128/labels/train2017/

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard

# Commented out IPython magic to ensure Python compatibility.
# %tensorboard --logdir runs

!python train.py --img 640 --batch 16 --epochs 300 --data coco128.yaml --cfg yolov5s.yaml --weights yolov5s.pt --nosave --cache

Image(filename='runs/exp0/train_batch1.jpg', width=900)

Image(filename='runs/exp0/test_batch0_gt.jpg', width=900)

Image(filename='runs/exp0/test_batch0_pred.jpg', width=900)

Image(filename='runs/exp0/results.png', width=900)

from utils.general import plot_results; plot_results(save_dir='./runs/exp0/')

!python detect.py --weights runs/exp1/weights/last.pt --img 416 --conf 0.4 --source inference/images/

Image(filename='inference/output/cat.jpg', width=900)